let data_res = [
    {
      id:1,
      image:"https://media-cdn.tripadvisor.com/media/photo-s/13/8c/34/cd/pluck.jpg",
      name:"Pluck",
      description:"Indian - European - Contemporary",
      price:"₹2,700 - ₹3,900",
      rating:4.2,
      location:"Asset No 2, New Delhi",
    },
    {
      id:2,
      name:"L'Osteria Bella",
      image:"https://media-cdn.tripadvisor.com/media/photo-m/1280/26/7e/15/38/interiors.jpg",
      description:"Italian - Pizza - Tuscan",
      price:"₹2,000 - ₹2,800",
      rating:3.9,
      location:"Aerocity, New Delhi",
    },
    {id:3,
      name:"Mister Chai",
      image:"https://media-cdn.tripadvisor.com/media/photo-w/11/65/0a/91/mister-chai-lounge.jpg",
      description:"Indian - Cafe - Halal",
      price:"₹2,600 - ₹3,200",
      rating:4.7,
      location:"Connaught Place, Delhi ",
    },
    {id:4,
      name:"Tamra",
      image:"https://media-cdn.tripadvisor.com/media/photo-o/18/b3/78/fa/tamra-restaurant.jpg",
      description:"Indian - Healthy - Asian",
      price:"₹2,700 - ₹4,100",
      rating:"5.0",
      location:"19 Ashoka Road, Delhi",
    },
    {id:5,
        name:"Raajsik",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/17/ae/68/f0/raajsik-indian-specialty.jpg",
        description:"Vegan - Halal - Gluten Free Options",
        price:"₹2,400 - ₹3,700",
        rating:4.1,
        location:"NH 48, New Delhi",
      },
      {id:6,
        name:"Thyme",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/13/1f/16/9f/thyme-a-multi-cuisine.jpg",
        description:"Indian - Bar - Seafood",
        price:"₹1,800 - ₹2,500",
        rating:3.8,
        location:"Rajokri Rd, New Delhi",
      },
      {id:7,
        name:"Veruan",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/28/77/25/b4/a-beautiful-small-quick.jpg",
        description:"Indian - Seafood - Fast food",
        price:"₹1,900 - ₹2,300",
        rating:4.4,
        location:"Kailash Colony, New Delhi",
      },
      {id:8,
        name:"Viva O' Viva",
        image:"https://media-cdn.tripadvisor.com/media/photo-m/1280/15/42/57/85/interior-decor.jpg",
        description:"Indian - Seafood - Vegetarian",
        price:"₹2,200 - ₹3,300",
        rating:"4.0",
        location:"Chanakyapuri, New Delhi",
      },
      {id:9,
        name:"Kiyan, The Roseate",
        image:"https://media-cdn.tripadvisor.com/media/photo-o/05/82/3e/19/kiyan-dusit-devarana.jpg",
        description:"Thai - Indian - Asian - Fusion",
        price:"₹3,100 - ₹4,000",
        rating:"5.0",
        location:"NH 8, New Delhi",
      },
  ];
  
  export default data_res;


  