let data_res = [
    {
      id:1,
      image:"https://media-cdn.tripadvisor.com/media/photo-s/13/8c/34/cd/pluck.jpg",
      name:"Pluck",
      description:"Indian, European, Contemporary",
      rating:4.2,
      location:"Delhi",
    },
    {
      id:2,
      name:"L'Osteria Bella",
      image:"https://media-cdn.tripadvisor.com/media/photo-m/1280/26/7e/15/38/interiors.jpg",
      description:"Italian, Pizza, Tuscan",
      rating:3.9,
      location:"Delhi",
    },
    {id:3,
      name:"Mister Chai",
      image:"https://media-cdn.tripadvisor.com/media/photo-w/11/65/0a/91/mister-chai-lounge.jpg",
      description:"Indian, Cafe, Halal",
      rating:60.00,
      location:"Delhi",
    },
    {id:4,
      name:"The Great Kabab Factory",
      image:"https://media-cdn.tripadvisor.com/media/photo-w/11/93/78/9c/photo0jpg.jpg",
      description:"Indian, Barbecue, Healthy, Fusion",
      rating:4.4,
      location:"Delhi",
    },
    {id:5,
        name:"Raajsik",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/17/ae/68/f0/raajsik-indian-specialty.jpg",
        description:"Vegan, Halal, Gluten Free Options",
        rating:4.1,
        location:"Delhi",
      },
      {id:6,
        name:"The Great Kabab Factory",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/11/93/78/9c/photo0jpg.jpg",
        description:"",
        rating:100.00,
        location:"Delhi",
      },
      {id:7,
        name:"The Great Kabab Factory",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/11/93/78/9c/photo0jpg.jpg",
        description:"",
        rating:100.00,
        location:"Delhi",
      },
      {id:8,
        name:"The Great Kabab Factory",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/11/93/78/9c/photo0jpg.jpg",
        description:"Indian, Barbecue, Healthy, Fusion",
        rating:100.00,
        location:"Delhi",
      },
      {id:9,
        name:"The Great Kabab Factory",
        image:"https://media-cdn.tripadvisor.com/media/photo-w/11/93/78/9c/photo0jpg.jpg",
        description:"",
        rating:100.00,
        location:"Delhi",
      },
  ];
  
  export default data_res;


  